name: Build and Push Docker Images

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allows manual triggering

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      # Build and push inventory service
      - name: Build and push Inventory Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./Backend
          file: ./Backend/Dockerfile.inventory
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/inventory-service:latest
      
      # Build and push payment service
      - name: Build and push Payment Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./Backend
          file: ./Backend/Dockerfile.payment
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/payment-service:latest
      
      # Optional: If you want to also push the docker-compose.yml configuration
      - name: Upload docker-compose.yml as artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-compose-config
          path: docker-compose.yml
          retention-days: 7